import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Upstash Workflow',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon-32x32.png',
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className='scroll-smooth'>
      <body className="antialiased text-sm sm:text-base">{children}</body>
    </html>
  )
}
